apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - codecentric-repo.yaml
  - ghost-repo.yaml
  - gitlab-repo.yaml
  - harbor.yaml
  - mesosphere-stable-repo.yaml
  - elastic-repo.yaml
  - bigbang.yaml